export {default as Navbar} from './Navbar'
export {default as Homepage} from './Homepage'
export {default as Cryptocurrencies} from './Cryptocurrencies'
export {default as CoinDetail} from './CoinDetail'
export {default as News} from './News'
export {default as Exchanges} from './Exchanges'
export {default as Loader} from './Loader'